--Set as EU or non-EU from country of residence

  CASE
    WHEN S.country_of_residence = 'Austria' THEN 'EU'
    WHEN S.country_of_residence = 'Belgium' THEN 'EU'
    WHEN S.country_of_residence = 'Bulgaria' THEN 'EU'
    WHEN S.country_of_residence = 'Croatia' THEN 'EU'
    WHEN S.country_of_residence = 'Cyprus' THEN 'EU'
    WHEN S.country_of_residence = 'Czech Republic' THEN 'EU'
    WHEN S.country_of_residence = 'Denmark' THEN 'EU'
    WHEN S.country_of_residence = 'England' THEN 'EU'
    WHEN S.country_of_residence = 'Estonia' THEN 'EU'
    WHEN S.country_of_residence = 'Finland' THEN 'EU'
    WHEN S.country_of_residence = 'France' THEN 'EU'
    WHEN S.country_of_residence = 'Germany' THEN 'EU'
    WHEN S.country_of_residence = 'Greece' THEN 'EU'
    WHEN S.country_of_residence = 'Hungary' THEN 'EU'
    WHEN S.country_of_residence = 'Ireland' THEN 'EU'
    WHEN S.country_of_residence = 'Italy' THEN 'EU'
    WHEN S.country_of_residence = 'Latvia' THEN 'EU'
    WHEN S.country_of_residence = 'Lithuania' THEN 'EU'
    WHEN S.country_of_residence = 'Luxembourg' THEN 'EU'
    WHEN S.country_of_residence = 'Malta' THEN 'EU'
    WHEN S.country_of_residence = 'Netherlands' THEN 'EU'
    WHEN S.country_of_residence = 'Northern Ireland' THEN 'EU'
    WHEN S.country_of_residence = 'Poland' THEN 'EU'
    WHEN S.country_of_residence = 'Portugal' THEN 'EU'
    WHEN S.country_of_residence = 'Romania' THEN 'EU'
    WHEN S.country_of_residence = 'Scotland' THEN 'EU'
    WHEN S.country_of_residence = 'Slovakia' THEN 'EU'
    WHEN S.country_of_residence = 'Slovenia' THEN 'EU'
    WHEN S.country_of_residence = 'Spain' THEN 'EU'
    WHEN S.country_of_residence = 'Sweden' THEN 'EU'
    WHEN S.country_of_residence = 'Wales' THEN 'EU'
    WHEN S.country_of_residence = 'UK' THEN 'EU'
    WHEN S.country_of_residence = 'United Kingdom' THEN 'EU'
    ELSE 'Non-EU'
  END AS [EU/Non-EU]
